### PR TITLE
Tejaswi/dev/2

### PR DESCRIPTION
**Pull request by rajsrivastava0710**
React Visualisation

### CODE REVIEW

**Comment by rajsrivastava0710** [comment]
@Tejaswi-19 , why did you remove some branches from the dropdown?

**Comment by rajsrivastava0710** [comment]
@Tejaswi-19 make that change in scrapper to this
const browser = await puppeteer.launch({ headless: false, ignoreHTTPSErrors: true});

**Comment by rajsrivastava0710** [comment]
Other than that, looks good to me. Make those changes and merge this PR.

**Comment by Tejaswi-19** [comment]
> @Tejaswi-19 , why did you remove some branches from the dropdown?

We didnt have data for other branches

**Pull request merged**
